/**
 * Expo config plugin: optional release signing for Gradle builds.
 *
 * When the environment variables below are present (e.g. from GitHub Actions
 * secrets) `./gradlew assembleRelease` signs with your upload keystore.
 * Otherwise it falls back to the debug keystore generated by React Native,
 * which still produces an installable APK for testing.
 *
 *   CHORDSET_UPLOAD_STORE_FILE      absolute path to the .jks/.keystore file
 *   CHORDSET_UPLOAD_STORE_PASSWORD
 *   CHORDSET_UPLOAD_KEY_ALIAS
 *   CHORDSET_UPLOAD_KEY_PASSWORD
 */
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @chordset/release-signing';

const RELEASE_SIGNING_CONFIG = `
        ${MARKER}
        release {
            if (System.getenv('CHORDSET_UPLOAD_STORE_FILE')) {
                storeFile file(System.getenv('CHORDSET_UPLOAD_STORE_FILE'))
                storePassword System.getenv('CHORDSET_UPLOAD_STORE_PASSWORD')
                keyAlias System.getenv('CHORDSET_UPLOAD_KEY_ALIAS')
                keyPassword System.getenv('CHORDSET_UPLOAD_KEY_PASSWORD')
            }
        }`;

function applyReleaseSigning(buildGradle) {
  if (buildGradle.includes(MARKER)) return buildGradle;

  const signingConfigs = /signingConfigs\s*\{/;
  if (!signingConfigs.test(buildGradle)) {
    throw new Error('[withAndroidReleaseSigning] signingConfigs block not found in app/build.gradle');
  }
  let result = buildGradle.replace(signingConfigs, (match) => `${match}${RELEASE_SIGNING_CONFIG}`);

  // Only the release build type uses the debug keystore in the React Native template.
  const releaseBlock = /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.debug/;
  if (!releaseBlock.test(result)) {
    throw new Error('[withAndroidReleaseSigning] release signingConfig not found in app/build.gradle');
  }
  result = result.replace(
    releaseBlock,
    `$1signingConfig System.getenv('CHORDSET_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
  );
  return result;
}

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error('[withAndroidReleaseSigning] only Groovy build.gradle is supported');
    }
    mod.modResults.contents = applyReleaseSigning(mod.modResults.contents);
    return mod;
  });
};

module.exports.applyReleaseSigning = applyReleaseSigning;
